/*  This file is part of the Proto programming language
 * 
 *  Copyright (c) 2023- Ntwali Bashige Toussaint
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#include <iostream>

#include "utils/lexer.h"
#include "common/token.h"
#include "common/token_type.h"

/**
 * Given the lexer, prints all the tokens generated by the lexer
 */
// void
// printTokens(struct Lexer * const lexer)
// {
//     unsigned line = 0;
//     for (;;) {
//         struct Token token = lexToken(lexer);

//         if (token.line != line) {
//             if (line == 0)
//                 printf("%4u ", token.line);
//             else
//                 printf("\n%4u ", token.line);
//             line = (unsigned) token.line;
//         } else {
//             printf("   \u2502 ");
//         }

//         if (token.type == PROTO_NEWLINE)
//             printf("%-20s \u21b5\n", tokenTypeToString(token.type));
//         else
//             printf("%-20s %.*s\n", tokenTypeToString(token.type), (int) token.length, token.start);

//         if (token.type == PROTO_EOF)
//             break;
//     }
// }
